package baog.enums;

public enum JiraAuthorities {
    PROJECT_MANAGER_AUTHORITY,
    TECHNICAL_MANAGER_AUTHORITY,
    CAN_CREATE_TASK,
    CAN_CHANGE_TASK_STATUS,
    CAN_ASSIGN_TASK,
    CAN_CREATE_PROJECT,
    CAN_VIEW_ALL_TASKS
}
